name: Sync main to personal fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push organization main to personal repo main
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "${{ secrets.EMAIL }}"
          git remote add personal https://kelly6226:${{ secrets.AUTO_ACTIONS }}@github.com/kelly6226/frontend.git
          git push personal main --force
