name: Storybook Deployment
run-name: ${{ github.actor }}의 스토리북 배포

on:
  push:
    branches:
      - feature/#1
  pull_request:
    branches:
      - feature/#1

jobs:
  storybook:
    runs-on: ubuntu-20.04
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-storybook

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR with Storybook URL
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "🚀 Storybook 링크: ${{ steps.chromatic.outputs.storybookUrl }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
